<?php
/**
 *    This file is part of OXID eShop Community Edition.
 *
 *    OXID eShop Community Edition is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    OXID eShop Community Edition is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @package   lang
 * @copyright (C) OXID eSales AG 2003-2012
 * @version OXID eShop CE
 * @translators: frajade, vikapera
 */

$sLangName  = "Français";

// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
'charset' => 'utf-8',
'ACCOUNT_PASSWORD_CONFIRMPASSWORD' => 'Confirmer le mot de passe',
'ACCOUNT_PASSWORD_PASSWORDMINLENGTH' => 'La longueur minimale du mot de passe est 6 de caractères.',
'ACCOUNT_RECOMM_LISTTITLE' => 'Titre',
'ACCOUNT_RECOMM_TITLE' => 'Mes listes de recommandations',
'ACCOUNT_USER_BILLINGADDRESS' => 'Adresse de livraison',
'ACCOUNT_USER_COMPLETEMARKEDFIELDS' => '(Merci de remplir tous les champs signalés par <span class="req">*</span>)',
'ACCOUNT_USER_ERRCOMLETEBILLINGADDRESS' => 'Erreur: Merci de préciser votre adresse de facturation.',
'ACCOUNT_USER_ERRCOMPLETEMARKEDFIELDS' => 'Erreur: Merci de remplir tous les champs désignés par <span class="req">*</span>.',
'ACCOUNT_USER_ERREMAILALREADYTAKEN' => 'Erreur: Cette adresse e-mail existe déjà!',
'ACCOUNT_USER_ERRINVALIDEMAIL' => 'Erreur: Adresse e-mail incorrecte',
'ACCOUNT_USER_ERRPASSWORDSDONTMATCH' => 'Erreur: les mots de passe sont incorrects',
'ACCOUNT_USER_ERRWRONGUSERNAMEPASSW' => 'Erreur: Mauvais identifiant / mot de passe',
'ACCOUNT_WISHLIST_BUYFORME1' => 'Bonjour, j\'ai déposé ici ma liste cadeaux',
'ACCOUNT_WISHLIST_BUYFORME2' => '. Je serai ravi(e) que tu m\'offres l\'un de ces produits.',
'ACCOUNT_WISHLIST_CLICKHERETOSENDWISHLIST' => 'Cliquez ici pour envoyer votre liste cadeaux à vos amis:',
'ACCOUNT_WISHLIST_ERRWRONGEMAIL' => 'Erreur lors de l\'envoi de l\'email. Merci de vérifier votre adresse email',
'ACCOUNT_WISHLIST_SEARCH' => 'Chercher',
'ACCOUNT_WISHLIST_SEND' => 'Envoyer',
'ACCOUNT_WISHLIST_SENDSUCCESSFULLY1' => 'Votre liste cadeaux a bien été envoyée à:',
'ACCOUNT_WISHLIST_SENDSUCCESSFULLY2' => 'envoyé!',
'ADD_RECOMM_ADDRECOMMLINK1' => 'Il n\'y a aucune liste de favoris pour le moment. Pour en créer une, cliquez',
'ADD_RECOMM_ADDRECOMMLINK2' => 'ici',
'BASKET_ARTICLENOTONSTOCK' => 'Ce produit est en rupture de stock, un réapprovisionnement est en cours.',
'BASKET_ARTNOMBER' => 'Ref. Art.:',
'BASKET_COUPONNOTACCEPTED1' => 'Votre bon d\'achat ',
'BASKET_COUPONNOTACCEPTED2' => 'a été refusé',
'BASKET_PAYMENTTAX1' => 'Frais additionnels TVA',
'BASKET_PLUSTAX1' => 'TVA frais de port ',
'BASKET_POPUP_ADDEDARTICLETOBASKET' => 'Vous venez d\'ajouter un produit dans votre panier.',
'BASKET_POPUP_FULL_ADDEDARTICLETOBASKET' => 'Vous venez d\'ajouter un produit dans votre panier.',
'BASKET_SHIPPINGNET' => 'Frais de port (hors TVA)',
'BASKET_TAX1' => 'plus TVA',
'BASKET_TSPROTECTIONCHARGETAX1' => 'plus TVA',
'BASKET_WRONGAMOUNT1' => 'Veuillez saisir une quantité valide',
'BASKET_WRONGAMOUNT2' => '.',
'byBrand' => 'Par marque/fabricant',
'byManufacturer' => 'Par marque/fabricant',
'byVendor' => 'Par distributeur',
'CONTACT_COMPLETEMARKEDFIELDS' => 'Merci de remplir tous les champs signalés par <span class="req">*</span>',
'CONTACT_COMPLETEMARKEDFIELDS2' => 'Merci de remplir tous les champs signalés par <span class="req">*</span>',
'CONTACT_SEND' => 'Message envoyé',
'CONTACT_THANKYOU1' => 'Merci.',
'CONTACT_THANKYOU2' => 'vos commentaires sont les bienvenus.',
'DETAILS_ARTNOMBER' => 'Ref. Art.:',
'DETAILS_LABEL' => 'Marque:',
'DETAILS_PLUSSHIPPING2' => 'Frais de livraison',
'DETAILS_PLUSSHIPPING_PLUS' => 'plus',
'DETAILS_PRICEALARM' => '<b>[!]</b> Alerte prix',
'DETAILS_PRICEALARM2' => '<b>[!]</b> Alerte prix',
'DETAILS_REDUCEDTEXT' => '(Prix normal.)',
'DETAILS_SEND' => 'Envoyer',
'DETAILS_VPE_MESSAGE_1' => 'Ce produit ne peut être commandé que par lot de',
'DETAILS_VPE_MESSAGE_2' => '--',
'DETAILS_ZOOM' => 'zoom [+]',
'EMAIL_INVITE_HTML_INVITETOSHOP' => 'Une invitation de la part de',
'EMAIL_INVITE_HTML_INVITETOSHOP2' => 'à découvrir',
'EMAIL_INVITE_HTML_INVITETOSHOP3' => '--',
'EMAIL_ORDER_CUST_HTML_ARTNOMBER' => 'Ref. Art.:',
'EMAIL_ORDER_CUST_HTML_NONE' => 'Aucun',
'EMAIL_ORDER_CUST_HTML_PAYMENTCHARGEVAT1' => 'TVA sur frais moyen de paiement',
'EMAIL_ORDER_CUST_HTML_PAYMENTMETHOD' => 'Le paiement sera effectué par:',
'EMAIL_ORDER_CUST_HTML_PLUSTAX1' => 'plus TVA',
'EMAIL_ORDER_CUST_HTML_PLUSTAX21' => 'plus TVA',
'EMAIL_ORDER_CUST_HTML_SHIPPINGCARRIER' => 'L\'envoi sera effectué par:',
'EMAIL_ORDER_CUST_HTML_SHIPPINGNET' => 'Frais de port (hors TVA)',
'EMAIL_ORDER_CUST_HTML_TAX1' => 'plus TVA',
'EMAIL_ORDER_CUST_HTML_TSPROTECTIONCHARGETAX1' => 'plus TVA',
'EMAIL_ORDER_CUST_HTML_YOURMESSAGE' => 'Ce que je voulais dire...:',
'EMAIL_ORDER_OWNER_HTML_MESSAGE' => 'Message:',
'EMAIL_ORDER_OWNER_HTML_PAYMENTINFOOFF' => '--',
'EMAIL_OWNER_REMINDER_HTML_ARTNOMBER' => 'N° produit:',
'EMAIL_SUGGEST_HTML_MENYGREETINGS' => 'Sincères salutations,',
'EXCEPTION_INPUT_NOTALLFIELDS' => 'Merci de remplir tous les champs signalés par <span class="req">*</span>',
'FACEBOOK_COMMENTS' => 'Commentaire Facebook',
'FACEBOOK_POPUP_CANCELBTN' => 'Annuler',
'FACEBOOK_POPUP_HEADER' => 'Mise à jour du compte client',
'FACEBOOK_POPUP_UPDATEBTN' => 'Mettre à jour le compte',
'FACEBOOK_POPUP_UPDATEDONETEXT' => 'Votre compte a bien été mis à jour. Dorénavant, quand vous utiliserez Facebook connect, vous serez automatiquement connecté avec votre compte.',
'FACEBOOK_POPUP_UPDATETEXT' => 'Vous êtes connecté via Facebook Connect. Si vous avez déjà un compte dans cette boutique,<br> veuillez saisir vos identifiants de connexion pour relier les 2 comptes entre eux.<br>Dorénavant, quand vous utiliserez Facebook connect, vous serez automatiq',
'FORGOTPWD_FORGOTPWD' => 'Vous avez oublié votre mot de passe ?',
'FORGOTPWD_TITLE' => 'Mot de passe oublié ?',
'FORGOTPWD_UPDATEPASSWORD' => 'Sauver votre mot de passe',
'FORM_WISHLIST_SUGGEST_ERRWRONGEMAIL' => 'Erreur lors de l\'envoi de l\'email. Merci de vérifier votre adresse email',
'fullDateFormat' => 'd-m-Y H:i:s',
'GUESTBOOKENTRY_TITLE' => 'Livre d\'or',
'GUESTBOOK_TITLE' => 'Livre d\'or',
'INC_ACCOUNT_HEADER_ADDRESS' => 'Mes adresses',
'INC_ACCOUNT_HEADER_LOGOUT' => '*DECONNEXION*',
'INC_ACCOUNT_HEADER_LOGOUTFROMSHOP' => 'Fermer votre session',
'INC_ACCOUNT_HEADER_PASSWORD' => 'Mon mot de passe',
'INC_ACCOUNT_HEADER_TOBASKET' => 'Dans le panier',
'INC_CMP_BASKET_QTY' => 'qté',
'INC_CMP_BASKET_QUANTITY' => 'Quantité',
'INC_CMP_FBCONNECT_LOGINBTNTEXT' => 'Connexion',
'INC_CMP_FBCONNECT_YOUARELOGGEDINAS' => 'Connecté en tant que',
'INC_CMP_LOGIN_ERRINVALIDEMAILORPWD' => '<b>Erreur:</b> <br>Mauvaise adresse e-mail ou mot de passe!',
'INC_CMP_LOGIN_FORGOTPWD' => 'Mot de passe oublié',
'INC_CMP_LOGIN_KEEPLOGGEDIN' => 'Rester connecté',
'INC_CMP_LOGIN_RIGHT_DETAILS' => 'DETAILS',
'INC_CMP_LOGIN_RIGHT_DETAILS2' => 'DETAILS',
'INC_CMP_LOGIN_RIGHT_DETAILS3' => 'DETAILS',
'INC_CMP_LOGIN_RIGHT_ERRINVALIDEMAILORPWD' => '<b>Erreur:</b> <br>Mauvaise adresse e-mail ou mot de passe!',
'INC_CMP_LOGIN_RIGHT_FORGOTPWD' => 'Mot de passe oublié',
'INC_CMP_LOGIN_RIGHT_KEEPLOGGEDIN' => 'Rester connecté',
'INC_CMP_LOGIN_RIGHT_LOGGEDINAS' => 'Vous êtes connecté sout le nom:',
'INC_CMP_LOGIN_RIGHT_LOGOUT' => 'Fermer votre session',
'INC_CMP_MINI_BASKET_QUANTITY' => 'Quantité',
'INC_CMP_NEWS_CONTINUE' => 'Continuer',
'INC_COMPARE_LOCATOR_DISPLAYPOPUP' => 'Aperçu avant impression',
'INC_FOOTER_GUESTBOOK' => 'Livre d\'or',
'INC_FOOTER_HOME' => 'Accueil',
'INC_FOOTER_PUBLICWISHLIST' => 'Liste cadeaux accessible à tous',
'INC_FOOTER_SOFTWAREANDSYSTEMBYOXID' => 'Logiciel et système ecommerce OXID eShop',
'INC_FOOTER_SOFTWAREFROMOXIDESALES' => 'Logiciel OXID eShop',
'INC_GUESTBOOK_LOCATOR_ENTRIESPERPAGE' => 'Entrées par page:',
'INC_GUESTBOOK_LOCATOR_PAGE' => 'PAGE',
'INC_HEADER_GUESTBOOK' => 'Livre d\'or',
'INC_HEADER_HOME' => 'Accueil',
'INC_HEADER_INCLTAXPLUSSHIPPING' => 'Tous les prix s\'entendent TTC (TVA incl.), hors frais de livraison',
'INC_HEADER_PRIVATWISHLIST' => 'Ma liste cadeaux',
'INC_HEADER_SERVICE' => 'Service',
'INC_LEFTITEM_CURRENCY' => 'Devise',
'INC_LEFTITEM_DISPLAYBASKET' => 'Afficher le contenu du panier',
'INC_LEFTITEM_PARTNERANDSEAL' => 'Partenaire et sigle',
'INC_LEFTITEM_PRODUCTSEARCH' => 'Recherche',
'INC_LIST_LOCATOR_ORDERSPERPAGE' => 'Commandes par page:',
'INC_LIST_LOCATOR_RECOMLISTSPERPAGE' => 'Listes par page:',
'INC_NEWBASKETITEM_ADDEDTOBASKET2' => 'a été ajouté au',
'INC_NEWBASKETITEM_ADDEDTOBASKET4' => '.',
'INC_NEWBASKETITEM_STOCKERROR1' => 'Ce produit est en rupture de stock, un réapprovisionnement est en cours.',
'INC_PRODUCT_VARIANTS_BACKTOMAINPRODUCT' => 'Retour à l\'apercu général',
'INC_PRODUCT_VARIANTS_OTHERVARIANTSOF' => 'Autres variantes de:',
'INC_PRODUCT_VARIANTS_VARIANTSELECTIONOF' => 'Variantes disponibles pour',
'INC_RECOMM_LISTS_MORE' => 'Détails',
'INC_RIGHTITEM_CURRENCY' => 'Devise',
'INC_RIGHTITEM_DISPLAYBASKET' => 'Afficher le contenu du panier',
'INC_RIGHTITEM_FBCONNECT' => 'Facebook Connect',
'INC_RIGHTITEM_HAVEPOUSEEN' => 'Dans le même genre...',
'INC_RIGHTITEM_SIMILARPRODUCTS' => 'Articles similaires',
'INC_RIGHTITEM_TOPOFTHESHOP' => 'Meilleures ventes',
'INC_RIGHTITEM_TS_RATINGS_BOX' => 'Evaluations clients',
'INC_RIGHTLIST_ORDERNOW' => 'Commander maintenant!',
'INC_SEARCHLEFTITEM_ALLCATEGORIES' => '- Toutes les catégories -',
'INC_SEARCHLEFTITEM_ALLDISTRIBUTORS' => '- Tous les vendeurs -',
'INC_SEARCHLEFTITEM_ALLMANUFACTURERS' => '- Tous les fabricants -',
'INC_SORT_GUESTBOOK_SORTBY' => 'Classé par',
'INC_SORT_SORTBY' => 'Classé par',
'INC_SORT_TITLE' => 'Titre',
'INC_STEPS_ITEM_CHANGEITEMS' => 'Modifier la quatité commandée<br>, effacer l\'article sélectionné<br>',
'INC_STEPS_ITEM_LASTSTEP1' => 'Terminé',
'INC_STEPS_ITEM_LASTSTEP2' => 'Votre commande est terminée',
'INC_STEPS_ITEM_LOGINSELECTBILLINGINFO' => 'Connexion, sélection des adresses à utiliser',
'INC_STEPS_ITEM_ORDER' => 'Commande',
'INC_STEPS_ITEM_SELECTSHIPPINGANDPAYMENT' => 'Mode de livraison,<br>moyen de paiement',
'INC_STEPS_ITEM_SEND' => 'Adresse',
'INC_STEPS_ITEM_SUBMITORDER' => 'Validation de la commande',
'INC_TRUSTEDSHOPS_ITEM_ALTTEXT' => 'En savoir plus',
'INC_VENDORLEFTITEM_BYMARK' => 'par marque/fabricant',
'INVITE_FROM' => 'De:',
'INVITE_MESSAGE1' => 'Bonjour, en naviguant sur le web',
'INVITE_MESSAGE2' => 'je suis tombé sur un site interessant. Clique sur le lien ci-après pour accéder au site.',
'INVITE_SEND' => 'Envoyer l\'invitation',
'INVITE_SENDEREMAIL' => 'E-Mail de l\'expéditeur',
'LIST_APPLYFILTER' => 'Appliquer le filtre',
'LIST_SELECTOTHERCATS1' => 'Sélectionnez d\'autres catégories -',
'LIST_SELECTOTHERCATS2' => 'et:',
'MALLSTART_LOCATION' => 'Vous êtes ici: / Sélectionnez votre boutique',
'MALLSTART_OXIDSOFTWARE' => 'Logiciel et programme OXID eSales',
'MALLSTART_OXIDSOFTWAREALT' => 'Logiciel et programme OXID eSales',
'MALLSTART_TITLE' => 'Sélectionnez votre boutique',
'MEDIA' => 'Fichiers média',
'MOREDETAILS_POPUP_TITLE' => 'Images Zoom',
'NEWSLETTER_COMPLETEALLFIELEDS' => 'Erreur: Merci de complèter les champs correctement',
'NEWSLETTER_COMPLETEMARKEDFIELEDS' => 'Merci de complèter tous les champs signalés par *!',
'NEWSLETTER_EMAIL_NOT_EXIST' => 'L\'adresse e-mail indiqué n\'est pas destinatrice de notre newsletter.',
'NEWSLETTER_FIRSTNAME' => 'Prénom',
'NEWSLETTER_INVALIDEMAIL' => 'Adresse e-mail incorrecte !',
'NEWSLETTER_STAYINFORMED' => 'Restez informés !',
'NEWS_LATESTNEWSBY' => 'Dernières nouveautés',
'ORDER_BILLINGADDRESS' => 'Adresse de facturation',
'ORDER_COUPONNOTACCEPTED1' => 'Votre bon d\'achat ',
'ORDER_COUPONNOTACCEPTED2' => 'n\'a pas été accepté',
'ORDER_DISCOUNTS_NOT_APPLIED_FOR_ARTICLES' => 'Les remises ne sont pas applicables sur ces produits',
'ORDER_GIFTOPTION' => 'Option cadeau',
'ORDER_IAGREETORIGHTOFWITHDRAWAL1' => 'J\'ai bien été informé de',
'ORDER_IAGREETORIGHTOFWITHDRAWAL3' => '--',
'ORDER_IAGREETOTERMS1' => 'J\'ai lu et accepte les',
'ORDER_IAGREETOTERMS3' => '--',
'ORDER_INFO_TITLE' => 'Comment commander?',
'ORDER_MODIFYADDRESS' => 'Modifier cette addresse',
'ORDER_MODIFYADDRESS2' => 'Modifier cette adresse',
'ORDER_MODIFYQUANTITY1' => 'Malheureusement un client plus rapide…',
'ORDER_MODIFYQUANTITY2' => 'a acheté cet article. Merci de modifier la quantité',
'ORDER_NOMBER' => '(N°.',
'ORDER_NONE' => 'Aucun',
'ORDER_NOTE' => 'Informations',
'ORDER_OTHERINTRESTINGARTICLES' => 'Autres produits susceptibles de vous interesser:',
'ORDER_PAYMENTCHARGETAX1' => 'TVA sur les frais',
'ORDER_PLUSSHIPPINGTAX1' => 'plus TVA',
'ORDER_PLUSTAX1' => 'plus TVA',
'ORDER_RIGHTOFWITHDRAWAL' => 'mon droit de rétractation',
'ORDER_RIGHTOFWITHDRAWAL_MOREINFO1' => 'Cliquez ici pour plus de détails concernant',
'ORDER_RIGHTOFWITHDRAWAL_TEXT' => 'Chaque consommateur peut révoquer sa déclaration contractuelle par écrit dans un délai de deux semaines sans justification de mtif<br>(ex: par lettre, fax, e-mail) ou bien en retournant les produits livrés <br>. Le délai de rétractation vaut à partir du j',
'ORDER_SEND' => 'Envoyer',
'ORDER_SHIPPINGADDRESS' => 'Adresse de livraison',
'ORDER_SHIPPINGANDPAYMENT' => 'Transporteur et moyen de paiement',
'ORDER_SHIPPINGGROSS1' => 'Expédition',
'ORDER_SHIPPINGNET' => 'Frais de livraison (hors TVA)',
'ORDER_TAX' => 'TVA',
'ORDER_TSPROTECTIONCHARGETAX1' => 'plus TVA',
'ORDER_UNITPRICE' => 'Prix à l\'unité',
'ORDER_VERIFYYOURINPUT' => 'Vérifiez les informations saisies!',
'ORDER_WRAPPINGTAX1' => 'plus TVA',
'ORDER_YOURMESSAGE' => 'Votre message:',
'PAYMENT_ACCOUNTNUMBER' => 'Numéro de compte:',
'PAYMENT_COMLETEALLFIELDS' => 'Merci de bien remplir tous les champs',
'PAYMENT_EMPTY_TEXT' => '<p>Un mode d\'envoi n\'est pas encore défini pour ce pays. Nous nous efforcons de trouver au plus vite les informations nécessaires pour organiser l\'envoi et vous tenons au courant des conditions d\'expédition. Merci dans ce cas de cliquez sur "Continuer"',
'PAYMENT_INCLUDEVAT' => 'TVA incl.',
'PAYMENT_PLUSCODCHARGE1' => 'plus',
'PAYMENT_PLUSCODCHARGE2' => 'Envoi contre remboursement',
'PAYMENT_SELECTEDSHIPPING' => 'Mode de livraison sélectionné:',
'PAYMENT_TSPROTECTIONTEXT' => 'La protection des acheteurs Trusted Shops sécurise vos achats en ligne. J\'accepte le transfert et',
'PAYMENT_TSPROTECTIONTEXT2' => 'la saisie ',
'PAYMENT_TSPROTECTIONTEXT3' => 'de mon adresse e-mail pour la protection des acheteurs Trusted Shops.',
'PAYMENT_TSPROTECTIONTEXT4' => 'Conditions',
'PAYMENT_TSPROTECTIONTEXT5' => 'pour la protection des acheteurs.',
'PAYMENT_UPDATESHIPPING' => 'Mise à jour des frais de livraison',
'PRICEALARM_BACKTOPRODUCT' => 'Retour au produit',
'PRICEALARM_THANKYOUMESSAGE1' => 'Merci.',
'PRICEALARM_THANKYOUMESSAGE2' => 'Vos commentaires sont les bienvenus.',
'PRICEALARM_THANKYOUMESSAGE3' => 'Nous vous informerons dès que le prix du produit',
'PRICEALARM_THANKYOUMESSAGE4' => 'atteindra',
'PRICEALARM_THANKYOUMESSAGE5' => '.',
'PRICEALARM_TITLE' => 'Alerte prix',
'priceFrom' => '<span class="prixfrom">à partir de</span>',
'PROMO_DAYS' => 'DAYS',
'PROMO_ONEDAY' => 'Un jour',
'PROMO_SOLDOUT' => 'Epuisé',
'PROMO_UPCOMING' => 'Prochainement',
'PROMO_WILLENDIN_PREFIX' => 'Fin dans',
'PROMO_WILLENDIN_SUFFIX' => '!',
'PROMO_WILLSTARTIN_PREFIX' => 'Débute dans',
'RECOMMLIST' => 'Liste de recommandations',
'RECOMMLIST_ALREADYRATED' => 'Vous avez déjà évalué!',
'RECOMMLIST_LISTREVIEW' => 'Donnez votre avis',
'RECOMMLIST_LOGGIN' => 'Connectez-vous pour laisser une évaluation!',
'RECOMMLIST_LOGGINTOWRITEREVIEW' => 'Connectez-vous pour laisser une évaluation!',
'RECOMMLIST_RATETHISLIST' => 'Evaluez cette liste!',
'RECOMMLIST_REVIEWNOTAVAILABLE' => 'Pas d\'évaluations pour l\'instant',
'RECOMMLIST_SEARCH' => 'Rechercher',
'RECOMMLIST_SELECTLIST' => 'Sélectionner une liste de vos produits favoris!',
'RECOMMLIST_WRITEREVIEW' => 'Écrire un commentaire',
'REGISTER_BILLINGADDRESS' => 'Adresse de facturation',
'REGISTER_CLICKHERE' => 'Cliquez ici!',
'REGISTER_COMPLETEMARKEDFIELDS' => '(Merci de remplir tous les champs signalés par <span class="req">*</span>)',
'REGISTER_COMPLETEMARKEDFIELDS2' => '(Merci de remplir tous les champs signalés par <span class="req">*</span>)',
'REGISTER_CONFIRMPWD' => 'Confirmer le mot de passe',
'REGISTER_DIFFERENTDELIVERYADDRESS' => 'Veuillez compléter les information suivantes si l\'adresse de livraison est différente de l\'adresse de facturation.',
'REGISTER_DIFFERENTSHIPPINGADDRESS' => 'Cliquez ici pour définir une adresse de livraison différente',
'REGISTER_ERRADDRESSUNKNOWN' => 'Erreur: Adresse inconnue',
'REGISTER_ERRALREADYREGISTERED' => 'Erreur: Vous avez déjà un compte client!',
'REGISTER_ERRCOMPLETEBILLINGADDRESS' => 'Erreur: Merci d\'indiquer l\'adresse de facturation.',
'REGISTER_ERRCOMPLETEMARKEDFIELDS' => 'Erreur: Merci de renseigner tous les champs désignés par <span class="req">*</span>.',
'REGISTER_ERRINVALIDEMAIL' => 'Erreur: Adresse e-mail incorrecte !',
'REGISTER_ERRLINKEXPIRED' => 'Le délai de confirmation de votre création de compte a expiré.',
'REGISTER_ERRMINLENGTH' => 'Erreur: La longueur minimale du mot de passe est de 6 caractères.',
'REGISTER_ERRPWDDONTMATCH' => 'Erreur: les mots de passe sont incorrects',
'REGISTER_ERRWRONGUSERORPWD' => 'Erreur: nom d\'identifiant / mot de passe incorrect',
'REGISTER_FORGOTPWD' => 'Mot de passe oublié ?',
'REGISTER_MOBIL' => 'Mobile:',
'REGISTER_OPENACCOUNT' => 'Créer un nouveau compte client',
'REGISTER_PRIVATPHONE' => 'Téléphone en soirée:',
'REGISTER_SHIPPINGADDRESS' => 'Adresse de livraison',
'REVIEW_PASTREVIEW' => 'Avis précédents',
'REVIEW_REVIEW' => 'Votre avis',
'REVIEW_THANKYOUFORREVIEW' => 'Merci pour votre commentaire',
'REVIEW_TOSAVEREVIEW' => 'Sauver',
'REVIEW_YOURREVIEW' => 'Votre commentaire',
'searchResult' => 'Résultats de la recherche pour "%s"',
'SECURITY_INFO_TITLE' => 'Protection des données',
'simpleDateFormat' => 'd-m-Y',
'START_LONGRUNNINGHITS' => 'Nos classiques',
'START_OURBARGAIN' => 'Nos bonnes affaires!',
'START_TITLE' => 'Accueil',
'SUGGEST_COMLETECORRECTLYFIELDS' => 'Merci de remplir tous les champs',
'SUGGEST_COMPLETEMARKEDFIELDS2' => 'Merci de remplir tous les champs signalés par <span class="req">*</span>',
'SUGGEST_MESSAGE1' => 'Bonjour, en navigant sur le web,',
'SUGGEST_MESSAGE2' => 'j\'ai découvert ce produit et j\'ai pensé qu\'il pourrait t\'intéresser. Clique sur le lien ci-dessous pour accéder à la boutique.',
'TAGS' => 'mots clé',
'TAGS_ADD' => 'Ajouter des mot-clés',
'TAGS_EDIT' => 'Modifier les mots clés',
'TAGS_HIGHLIHGT_INSTRUCTIONS' => 'Cliquez les mots clé et saisir les nouveaux',
'TAGS_SEPARATEBY' => 'Séparés les mots clés avec les caractères suivants',
'THANKYOU_BACKTOSHOP' => 'Retour dans la boutique',
'THANKYOU_LOCATION' => 'Commande terminée',
'THANKYOU_ORDERHISTORY' => 'Votre historique de commandes',
'THANKYOU_REGISTEREDYOUORDERNO1' => 'Votre commande porte le n°:',
'THANKYOU_REGISTEREDYOUORDERNO2' => '--',
'THANKYOU_THANKYOU1' => 'Merci pour votre commande',
'THANKYOU_THANKYOU2' => 'dans',
'USER_BILLINDADDRESS' => 'Adresse de facturation',
'USER_BIRTHDAYMESSAGE' => 'Donnez-nous votre date de naissance<br>afin que nous puissions vous faire une surprise.',
'USER_BLOCHED_TITLE' => 'Accès refusé',
'USER_COMPLETEALLMARKEDFIELDS' => '(Merci de remplir  tous les champs signalés par <span class="req">*</span>)',
'USER_CONFIRMPWD' => 'Confirmer le mot de passe',
'USER_DIFFERENTDELIVERYADDRESS' => 'Veuillez complèter les informations suivantes si l\'adresse de livraison est différente de l\'adresse de facturation.',
'USER_DIFFERENTSHIPPINGADDRESS' => 'Cliquez ici pour définir une autre adresse de livraison',
'USER_ENTEREMAILANDPWD' => 'Veuillez saisir votre adresse e-mail et votre mot de passe.',
'USER_ERRALREADYREGISTERED' => 'Erreur: Vous avec déjà un compte client. Saisissez votre mot de passe.',
'USER_ERRALREADYREGISTERED2' => 'Erreur: Vous avec déjà un compte client. Saisissez votre mot de passe.',
'USER_ERRCOMLETEMARKEDFIELDS' => 'Merci de remplir tous les champs signalés par <span class="req">*</span>',
'USER_ERRCOMPLETEBILLINGADDRESS' => 'Erreur: Veuillez indiquer également l\'adresse de facturation.',
'USER_ERRCOMPLETEFIELDS' => '<b>Erreur:</b> Veuillez compléter votre adresse de facturation.',
'USER_ERRINVALIDEMAIL' => '<b>Erreur:</b> Adresse e-mail non correcte !',
'USER_ERRINVALIDEMAIL2' => 'Erreur: Adresse e-mail incorrecte',
'USER_ERRMINPWDLENGTH' => 'Erreur: La longueur minimale du mot de passe est de 6 caractères.',
'USER_ERROR' => '<b>Erreur:</b>',
'USER_ERRPASSWORDSDONTMATCH' => '<b>Erreur:</b> Les mots de passe sont incorrects.',
'USER_ERRPWDDONTMATCH' => 'Effeur: Les mots de passe sont incorrects',
'USER_ERRUNKNOWNADDRESS' => '<b>Erreur:</b> Adresse inconnue!',
'USER_ERRUNKNOWNADDRESS2' => 'Erreur: Adresse inconnue!',
'USER_ERRWRONGUSERORPWD' => '<b>Erreur:</b> Mauvais login/mot de passe.',
'USER_ERRWRONGUSERORPWD2' => 'Erreur: Mauvais indentifiant / mot de passe.',
'USER_FB_UPDATEACCOUNTMSG' => 'Vous êtes déjà utilisateur de Facebook connect. Si vous avez déjà un compte, merci de mettre à jour votre compte et de vous connecter par l\'intermédiare de Facebook la prochaine fois.',
'USER_FORGOTPWD' => 'Mot de passe oublié',
'USER_LOGIN2' => 'Connexion',
'USER_MOBIL' => 'Téléphone portable:',
'USER_OPENPERSONALACCOUNT1' => 'Créer un compte client.',
'USER_OPENPERSONALACCOUNT10' => '- L\'accès aux offres spéciales',
'USER_OPENPERSONALACCOUNT2' => 'Un compte client permet à son détenteur',
'USER_OPENPERSONALACCOUNT3' => 'des avantages tels que:',
'USER_OPENPERSONALACCOUNT4' => '- Les gestion de ses adresses',
'USER_OPENPERSONALACCOUNT5' => '- Le suivi de commandes',
'USER_OPENPERSONALACCOUNT6' => '- L\'historique des commandes',
'USER_OPENPERSONALACCOUNT7' => '- Les listes d\'envies',
'USER_OPENPERSONALACCOUNT8' => '- Les listes de sélections',
'USER_OPENPERSONALACCOUNT9' => '- L\'abonnement à la newsletter',
'USER_OPTION1' => 'Option 1',
'USER_OPTION2' => 'Option 2',
'USER_OPTION3' => 'Option 3',
'USER_ORDERWITHOUTREGISTER1' => 'Acheter sans se connecter',
'USER_ORDERWITHOUTREGISTER2' => '(Je ne veux pas créer de compte client)',
'USER_PLEASELOGIN' => 'Connectez-vous en saisissant votre adresse e-mail ou votre numéro de client et votre mot de passe',
'USER_PRIVATPHONE' => 'Téléphone en soirée:',
'USER_RECEIVECONFIRMATION' => 'Vous recevrez un confirmation d\'enregistrement avec vos identifiants de connexion. Veuillez conserver ces information en lieu sûr.',
'USER_SEND' => 'Envoyer',
'USER_SHIPPINGADDRESS' => 'Adresse de livraison',
'USER_UPDATE_ACCOUNT' => 'Mettre à jour le compte',
'USER_USEBILLINGADDR' => 'Utiliser l\'adresse de facturation',
'usrRegistered' => 'L\'identifiant sera enregistré après avoir fourni son mot de passe',
'VAT_MESSAGE_ID_NOT_VALID' => 'Erreur: Ce n° de siret n\'est pas correct',
'VAT_MESSAGE_ID_VALID' => 'Ce n° de siret n\'est pas correct',
'VAT_MESSAGE_INVALID_INPUT' => 'Le code pays fourni n\'est pas correct ou bien le numéro de TVA n\'est pas saisi',
'VAT_MESSAGE_MS_UNAVAILABLE' => 'Le service de vérification des n° de siret est indisponible actuellement, veuillez  réessayer ultérieurement',
'VAT_MESSAGE_SERVER_BUSY' => 'Le service de vérification des n° de siret n\'a pas répondu. Veuillez  réessayer ultérieurement.',
'VAT_MESSAGE_SERVICE_UNAVAILABLE' => 'Le service SOAP est actuellement indisponible, veuillez  réessayer ultérieurement.',
'VAT_MESSAGE_TIMEOUT' => 'Le service de vérification des n° de siret ne répond pas actuellement, veuillez  réessayer ultérieurement',
'WISHLIST_PRODUCTS1' => 'Ces produits sont dans la liste de souhaits de',
'WISHLIST_PRODUCTS2' => '. Si vous souhaitez faire plaisir à cette personne, offrez-lui tout ou une partie de cette liste.',
'WRAPPING_ADDFORANDFROM' => 'Merci d\'ajouter également "Pour" et "De la part de".',
'WRAPPING_ADDWRAPORCARD' => 'Ajouter un emballage cadeau et / ou une carte de voeux',
'WRAPPING_BACKTOORDER' => 'Retour à la commande',
'WRAPPING_GIFTOPTION' => 'Option cadeau',
'WRAPPING_NONE' => 'Aucun',
'WRAPPING_OPTIONALMESSAGE' => 'Vous pouvez saisir ici optionellement le message à joindre à votre envoi:',
'WRAPPING_PACKASGIFT' => 'Emballage cadeau',
'WRAPPING_PRICEPERPACKAGE' => 'Prix par lot',
'WRAPPING_SELECTCARD' => 'Sélectionnez une carte',
'WRAPPING_TITLE' => 'Papier cadeau',
'ACCOUNT_PASSWORD_ERRINCORRECTCURRENTPASSW'                   => 'Erreur: Votre mot de passe actuel est erroné.',

'EMAIL_SENDEDNOW_HTML_ORDERSHIPPEDTO'                         => 'Adresse de livraison: ',
'EMAIL_SENDEDNOW_HTML_ORDERNOMBER'                            => 'N° Commande.:',
'EMAIL_SENDEDNOW_HTML_QUANTITY'                               => 'Quantité',
'EMAIL_SENDEDNOW_HTML_PRODUCT'                                => 'Produit',
'EMAIL_SENDEDNOW_HTML_PRODUCTRATING'                          => 'Rating',
'EMAIL_SENDEDNOW_HTML_REVIEW'                                 => 'Submit rating',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKING'                       => 'suivi d`envoi',
'EMAIL_SENDEDNOW_HTML_SHIPMENTTRACKINGURL'                    => 'Sur la site internet de DHL. Notez qu’il n’est parfois possible de consulter le suivi du colis qu’après 24 heures.',
'EMAIL_SENDEDNOW_HTML_ARTNOMBER'                              => 'N° d`article',




);
